name: Upload changed files to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Permite ver los cambios recientes para git diff

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get changed and deleted files
      run: |
        git diff --name-only HEAD~1 HEAD > changed_files.txt
        git diff --diff-filter=D --name-only HEAD~1 HEAD > deleted_files.txt

    - name: Upload changed files to S3
      run: |
        while read file; do
          if [ -f "$file" ]; then
            aws s3 cp "$file" "s3://www.fremitech.com/www.fremitech.com/$file"
          fi
        done < changed_files.txt
        
    - name: Delete removed files from S3
      run: |
        while read file; do
          aws s3 rm "s3://www.fremitech.com/www.fremitech.com/$file"
        done < deleted_files.txt
